#!/bin/bash

green () {
    echo -e "\e[32m $1 \033[0m" $2;
}

error () {
    echo -e "\e[41;37m $1 \033[0m" $2;
}

github_pub(){
    green "正在 git 到 GitHub"
    git add . ;git commit -am "$(date +%y-%m-%d_%H:%M:%S)";git push 1> /dev/null
    if [ $? -eq 0 ];then
        green "提交成功"
        green "API: " "https://raw.githubusercontent.com/xyz349925756/sub-api/main/newcdnip.txt"
    else
        error "提交失败，参考返回失败信息！"
    fi
}

github_pub